/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sister2project;

import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Imburden
 */
public class Sister2GUI extends javax.swing.JFrame {
    final static String MAINMENU = "Main Menu";
    final static String GAME = "Game";
    final static String TRADEBOX = "Trade Box";
    final static String OFFERITEM = "Offer Item";
    final static String FINDITEM = "Find Item";
    final static String FINDRESULTS = "Find Results";
    
    JPanel cards;
    JFrame frame;
    
    /**
     * Creates new form Sister2GUI
     * @throws java.lang.InterruptedException
     */
    public Sister2GUI() throws InterruptedException {
        initComponents();
        
        frame = new JFrame("Kuda Horizon");
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        cards = new JPanel(new CardLayout());
        
        Sister2GUI_MainMenu card1 = new Sister2GUI_MainMenu();
        Sister2GUI_Game card2 = new Sister2GUI_Game();
        Sister2GUI_TradeBox card3 = new Sister2GUI_TradeBox();
        Sister2GUI_OfferItem card4 = new Sister2GUI_OfferItem();
        Sister2GUI_FindItem card5 = new Sister2GUI_FindItem();
        Sister2GUI_FindBox card6 = new Sister2GUI_FindBox();
                
        card1.AddButtonClickEvents(cards);
        card2.AddButtonClickEvents(cards);
        card3.AddButtonClickEvents(cards);
        card4.AddButtonClickEvents(cards);
        card5.AddButtonClickEvents(cards);
        card6.AddButtonClickEvents(cards);
        
        cards.add(card1, MAINMENU);
        cards.add(card2, GAME);
        cards.add(card3, TRADEBOX);
        cards.add(card4, OFFERITEM);
        cards.add(card5, FINDITEM);
        cards.add(card6, FINDRESULTS);
        
        frame.add(cards);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sister2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sister2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sister2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sister2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Sister2GUI().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Sister2GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
